language: cpp

matrix:
  include:
    - os: linux
      env:
        - QT: 59
    - os: osx
      env:
        - QT: 510

before_install:
 - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:$PPA'
 - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
 - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt$QT-meta-full'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt$QT'
 - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$QT'

script:
 - '[ "$TRAVIS_OS_NAME" != linux ] || . /opt/qt$QT/bin/qt$QT-env.sh'
 - '[ "$TRAVIS_OS_NAME" != linux ] || cmake . -DCMAKE_BUILD_TYPE=Release'
 - '[ "$TRAVIS_OS_NAME" != osx ] || cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=`brew --prefix qt$QT`'
 - make
